(defun check_max(lis1)
    (setq max -9999999)
    (loop for j from 0 to (- (length lis1) 1)
        do(progn 
            (if (< max (nth j lis1))
                (setq max (nth j lis1) )
            )
        )
    )
    (if (> max -9999999)
        (return-from check_max max)
    )
    ;; (format t "xmax ~d" max)
)

(setf x (list 5 6 8 1 4 2 33 65 5 ))
;; (print x)
;; (setf x (list 5 6 8 1))
;; (print x)
;; (print (check_max x))
;; (setq k (check_max x))
;; (print k)
;; (print (cdadr x))
;; (terpri)
;; ;; (print (sort x))
;; (print x)
;; (print (remove 8 x))

(setf lis2 (list -1245789) )
(print x)
(setf len (length x))
;; (print len)
(loop for i from 0 to (- len 1)
do(progn
    ;; (format t " max ~d ~%" (check_max x))
    (setq k (check_max x))
    ;; (setf lis2 (append (list k) lis2))
    (setf lis2 (cons k lis2))
    (setf x (remove k x))
))
(setf lis2 (cdr lis2))
(setq n (- (length lis2) 1))
;; (print n)
;; (print (remove (nth n lis2) lis2))
(setf lis2 (remove (nth n lis2) lis2))
(format t "~%Sorted list is ~d " lis2)